name: Rust

on:
  push:
    tags:
      - "*"
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # 安装必需的依赖
    - name: Set up OpenSSL and build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          make \
          musl-tools \
          libssl-dev \
          pnpm
    
    # 编译 frontend
    - name: Build frontend
      run: |
        cd frontend
        pnpm install
        pnpm run build
    
    # 编译普通版本
    - name: Build Rust Project (default)
      run: cargo build --verbose
    
    # 编译 Release 版本
    - name: Build Release Version
      run: cargo build -r --verbose
    
    # 编译目标为 musl 版本
    - name: Build musl target
      run: cargo build -r --target=x86_64-unknown-linux-musl --verbose
    
    # 运行测试
    - name: Run tests
      run: cargo test --verbose
